#!/bin/bash
echo "$@"
#set -x
set -u
set -e
command="$@"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
echo $DIR/sns_wrapper.sh $command
at now <<EOF
$DIR/sns_wrapper.sh $command
EOF
