---
- name: Get UCLDC operator keys to account, no need for master key
  sudo: no
  get_url:
    url: https://raw.github.com/ucldc/appstrap/master/cdl/ucldc-operator-keys.txt
    dest: ~/.ssh/ucldc_operator_keys
    force: no
- name: get lines for adding to authorized_keys
  sudo: no
  shell: tail -n+2 ~/.ssh/ucldc_operator_keys
  register: operator_keys
- 
  name: "Add UCLDC operator keys to authorized_keys"
  blockinfile: 
    dest: ~/.ssh/authorized_keys
    block: "{{ operator_keys.stdout }}"
    state: present
  sudo: false
- name: "Add M McKinley key"
  lineinfile:
    dest: ~/.ssh/authorized_keys
    state: present
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK5pfP/RNh866vqNhLjZDu26MsZAIASGpD1e+YO1Pbg8y0nPaCJoFiFbD3fwM+b8FBNsoUNWuuWULtqMquhWE6whLM7ZcPuXDxDxRh/VPQV1NNJ7GKlBk9dhp8LiZ8sMOtQKkUWVC1jZ7BVjhXe7NhSC2xVn9nA9djvnDpnBtwUmdxNHDfhXje3Yrpc0f94wXkXB21Ki9MhF/yAEhM7AUvO3G9tBOmShI/K9BbrjqU2DW0f9vaBGcwH5aYOHsXYzboB5L77B99aUVXYYmjfbLNhYfmfDUV2uMpTU50W2ZJ/aHz5DlAI4U4zyad29rquJQxToDQPKyj8428pBHR180n mmckinle@CDL-MMCKINL-9M.local"
- name: "Add GAMontoya key"
  lineinfile:
    dest: ~/.ssh/authorized_keys
    state: present
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRp7Z1dTG+UvuSCe+3u1zVtvG759Lg/j9bvmNIZEZiUXbQ6k6bg8/ckeRR1qFGU7wVtgvJ+Ns1h28wuTRRsOwSirFz+4jE66mnPqb6MPM9zZSRLqHGUgvVm0GQ7TUQ7Yd+C9TEN+z7YoM0fwSRg0Qi4fBr8uEst2m2ZBBVz76VKB3agSzXngOhE2+PRg3KbkR9H9eQ6ejzJLjdlKMAZkRwwx+Ng12b2P0IwXX3Rko4HDGRHvP9qbmtq24Sg0uAmnGxWDE8lFjSizNxv/ULrGscSxS5uKliKrt84StTnDIhjOVMGlCBqjQ6a7Px3Kj54VQXUm2gFnsb/7m+VZNVIYEv gamontoya@mac11606.ucsd.edu"
- name: "Add Mark's latest macbook key"
  lineinfile:
    dest: ~/.ssh/authorized_keys
    state: present
    line: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCl4+GEZh3VQ8JiGS79oazNQgn2grhkgLHgEmQcXkK0AxhuWKvFqIo0w08D+iNsW0pC4hRFUqF7VzfQ9f3T/wCIaAW1AwnZQh5jTccrH2yJvpQ7JAb+3AdF6nM1dCC19h2ugCZWJjzLRMzsYV2OWjF9YCOabVH59XsHgTLmfv3IkE3hSr8G+bn0zPL7q8in+c/QOGoM/Lq3wm2tXuRYGbbd0PXS1x56o3tGzokqrWHldVTmhOf5hLGrLQWYh9WCY4VcnZmUGYesnSWPnsbN8jPSGXNJzZwdnP3ip+Ub5qllPSMi3Z/xOORSsixwjpUm6VlexqLN1FpvTiYP89GQxYKP mredar@cdl-mredar-9m.ucop.edu"
- name: "Add Adrian's Key"
  lineinfile:
    dest: ~/.ssh/authorized_keys
    state: present
    line: "AAAAB3NzaC1yc2EAAAABJQAAAQEA1czCmAZM2WOip8PYgWYN/ewlZoYYy2zO66yO60VUiP3q1KQQ7JQCF06DYwO3U0AZ1H8c6UtIRZpe8g3UpTAX/tTvASXy1bVS+bV5FDlxU9723Iyc2/vcGIciTtFzb4QQfacmXsjKheOs0DR++jUrBuYsd4xjBsQRfSzdmcZDK6BxDdA1T3k0KJ2ShuEGCYVuC8ZyzwHO2Ih8/7zVIqmyXjJ2T/fBndTME2ZJrYWpH9bMRgYh/KBF91cxLx3Udlvqvqswh+M4Fe/vqZtgZ//n+Mt3iutZ4Dzf12w5n78H11kuVXkPv58AGZbavj9PHZD2WZzmvm2f8IgN/WC+oFfwkQ== rsa-key-20151014-aturner"
