---
# http://codepoets.co.uk/2014/ansible-random-things/
- name: clear previous instance ips if they match
  local_action: command  ssh-keygen -f "~/.ssh/known_hosts" -R {{ item.private_ip }}  
  with_items: "{{ ec2_info.instances }}"
- name: Wait for SSH to come up
  wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2_info.instances }}"

