---
# vars file for provision_worker
ansible_user: ec2-user
path_tiffcp: /usr/bin/tiffcp
path_magick_convert: /usr/bin/convert
path_kdu_compress: /usr/bin/kdu_compress
path_tiff2rgba: /usr/bin/tiff2rgba
path_tifficc: /usr/bin/tifficc
