# Create new worker instance for ingest
# This will launch into the private VPC and use the private addresses
# for redis, couchdb and solr
#
---
#- hosts: localhost
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
      name_suffix: -prod
      sec_grp_ingest_private_id: sg-95b298f0
      subnet_id_private: subnet-1bbe676c
      worker_instance_type: t2.micro
      ondemand: true
  roles:
    - create_worker_instance
#doesn't work, not yet in ec2.py inventory - include: provision_worker.yml


