---
- hosts: couchdb
  become: yes
  gather_facts: yes
  vars:
    role: couchdb
    dir_role_templates: "roles/{{ role }}/templates"
  pre_tasks:
    - name: check if extra disk already in fstab?
      shell: grep -c /dev/xvdb /etc/fstab 
      register: infstab
      failed_when: infstab.rc > 1
    - { include: roles/couchdb/tasks/mount_data_volume.yml,
        when: infstab.rc == 1 }
  roles:
    - { role: mredar.nightly_security_update_yum, tags: security-up }
    - common
    - couchdb
