---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    role: majorTom
    dir_role_templates: "roles/{{ role }}/templates"
  roles:
    - { role: mredar.nightly_security_update_yum, tags: security-up }
    - { role: common, become: no, tags: common}
    - { role: worker, become: no, tags: worker}
    - { role: majorTom, become: no, tags: [ majorTom, bashrc ]}
