---
# Remove the container & image for solr, in prep for rebuild.
# Remove index as well
# tasks file for solr5_docker_rm
- name: remove the running container
  become: yes
  docker: 
    name: solr
    image: "{{ docker_image_name }}"
    state: absent
- name: remove the docker image
  become: yes
  docker_image:
    name: "{{ docker_image_name }}"
    state: absent
- debug:
    msg : "DIR INDEX:{{ dir_index }}"
- name: remove the index files
  shell: rm -rf {{ dir_index }}/*
  tags: rm_index
